# Generated by Django 6.0.8 on 2026-09-21 10:53

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_name', models.CharField(max_length=300)),
                ('checksum', models.CharField(max_length=64, unique=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('imported_rows', models.PositiveIntegerField(default=0)),
                ('skipped_rows', models.PositiveIntegerField(default=0)),
                ('warnings', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=80)),
                ('location_type', models.CharField(choices=[('building', 'Building'), ('laboratory', 'Laboratory'), ('cabinet', 'Cabinet / storage unit'), ('shelf', 'Shelf')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='inventory.location')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reagent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('formula', models.CharField(blank=True, max_length=200)),
                ('cas_number', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\d{2,7}-\\d{2}-\\d$', 'Enter a CAS number such as 67-64-1.')])),
                ('description', models.TextField(blank=True)),
                ('catalog_number', models.CharField(blank=True, max_length=120)),
                ('physical_state', models.CharField(choices=[('solid', 'Solid'), ('liquid', 'Liquid'), ('gas', 'Gas'), ('mixture', 'Mixture'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('default_unit', models.CharField(blank=True, max_length=20)),
                ('sds_url', models.URLField(blank=True, max_length=500)),
                ('source_sheet', models.CharField(blank=True, max_length=200)),
                ('source_row', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reagents', to='inventory.category')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reagents', to='inventory.supplier')),
            ],
            options={
                'ordering': ['name'],
                'permissions': [('view_attention', 'Can view items requiring attention')],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('barcode', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('lot_number', models.CharField(blank=True, max_length=120)),
                ('initial_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('concentration', models.CharField(blank=True, max_length=120)),
                ('received_at', models.DateField(blank=True, null=True)),
                ('opened_at', models.DateField(blank=True, null=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'In stock'), ('low_stock', 'Low stock'), ('reserved', 'Reserved'), ('pending_review', 'Pending review'), ('not_found', 'Not found'), ('written_off', 'Written off')], default='available', max_length=20)),
                ('label_photo', models.ImageField(blank=True, upload_to='labels/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('source_key', models.CharField(blank=True, max_length=300, null=True, unique=True)),
                ('raw_quantity', models.CharField(blank=True, max_length=120)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='inventory.location')),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_packages', to=settings.AUTH_USER_MODEL)),
                ('reagent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='inventory.reagent')),
            ],
            options={
                'ordering': ['reagent__name', 'created_at'],
                'permissions': [('use_package', 'Can use package stock'), ('move_package', 'Can move packages'), ('write_off_package', 'Can write off packages')],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('import', 'Import'), ('add', 'Addition'), ('use', 'Use'), ('adjust', 'Adjustment'), ('move', 'Move'), ('write_off', 'Write off')], max_length=20)),
                ('quantity_before', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('quantity_delta', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('quantity_after', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_from', to='inventory.location')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.package')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_to', to='inventory.location')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('parent', 'code'), name='unique_location_code_per_parent'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['status'], name='inventory_p_status_f7cab0_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['expires_at'], name='inventory_p_expires_b5a023_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['package', 'created_at'], name='inventory_s_package_17bd38_idx'),
        ),
        migrations.AddIndex(
            model_name='reagent',
            index=models.Index(fields=['name'], name='inventory_r_name_1e78f3_idx'),
        ),
        migrations.AddIndex(
            model_name='reagent',
            index=models.Index(fields=['cas_number'], name='inventory_r_cas_num_49620d_idx'),
        ),
    ]
